# Generated by Django 5.2 on 2026-05-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0024_backfill_token_usage_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='is_reasoning_model',
            field=models.BooleanField(default=False, help_text='启用后，使用 ChatDeepSeek 包装器处理 reasoning_content 字段，适用于 DeepSeek-R1、MIMO 等推理模型。系统也会根据模型名称自动检测（如包含 deepseek-reasoner、mimo 等关键词）', verbose_name='推理模型'),
        ),
    ]
