# Generated by Django 5.2 on 2026-06-23 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0025_add_is_reasoning_model'),
        ('langgraph_integration', '0025_alter_llmconfig_provider'),
    ]

    operations = [
    ]
