# Generated by Django 5.2 on 2026-07-10 09:29

import django.db.models.deletion
import knowledge.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0024_update_reranker_and_chunk_choice_labels'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Document'},
        ),
        migrations.AlterModelOptions(
            name='documentchunk',
            options={'ordering': ['document', 'chunk_index'], 'verbose_name': 'Document chunk', 'verbose_name_plural': 'Document chunk'},
        ),
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Knowledge base', 'verbose_name_plural': 'Knowledge base'},
        ),
        migrations.AlterModelOptions(
            name='knowledgeglobalconfig',
            options={'verbose_name': 'Knowledge global config', 'verbose_name_plural': 'Knowledge global config'},
        ),
        migrations.AlterModelOptions(
            name='querylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Query log', 'verbose_name_plural': 'Query log'},
        ),
        migrations.AlterField(
            model_name='document',
            name='business_domain',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Business domain'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_stage',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Document stage'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('doc', 'Word (legacy)'), ('xlsx', 'Excel'), ('xls', 'Excel (legacy)'), ('pptx', 'PowerPoint'), ('txt', 'Text'), ('md', 'Markdown'), ('html', 'HTML'), ('url', 'URL')], max_length=10, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Error message'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=knowledge.models.document_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='File size'),
        ),
        migrations.AlterField(
            model_name='document',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.knowledgebase', verbose_name='Knowledge base'),
        ),
        migrations.AlterField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='document',
            name='module',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='document',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Page count'),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processed at'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Document title'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='document',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Word count'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_index',
            field=models.PositiveIntegerField(verbose_name='Chunk index'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_level',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], default='child', max_length=10, verbose_name='Chunk level'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.document', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Embedding hash'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='end_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='End index'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='heading_path',
            field=models.JSONField(blank=True, default=list, help_text="Structural heading path, e.g. ['H1 title', 'H2 title', 'H3 title'].", verbose_name='Heading path'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Page number'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='parent_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.documentchunk', verbose_name='Parent chunk'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='start_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Start index'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='vector_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vector ID'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='child_chunk_overlap',
            field=models.PositiveIntegerField(blank=True, help_text='Override global child chunk overlap. Null uses global default.', null=True, verbose_name='Child chunk overlap'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='child_chunk_size',
            field=models.PositiveIntegerField(blank=True, help_text='Override global child chunk size. Null uses global default.', null=True, verbose_name='Child chunk size'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_bases', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Knowledge base name'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='parent_chunk_overlap',
            field=models.PositiveIntegerField(blank=True, help_text='Override global parent chunk overlap. Null uses global default.', null=True, verbose_name='Parent chunk overlap'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='parent_chunk_size',
            field=models.PositiveIntegerField(blank=True, help_text='Override global parent chunk size. Null uses global default.', null=True, verbose_name='Parent chunk size'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='projects.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='api_base_url',
            field=models.CharField(blank=True, help_text='Embedding endpoint, for example https://api.openai.com/v1 or http://xinference:9997.', max_length=500, null=True, verbose_name='Embedding API URL'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='Authentication key for the embedding service.', max_length=500, null=True, verbose_name='Embedding API key'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='child_chunk_overlap',
            field=models.PositiveIntegerField(default=200, help_text='Character overlap between child chunks.', verbose_name='Child chunk overlap'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='child_chunk_size',
            field=models.PositiveIntegerField(default=800, help_text="Character count for child chunks. Should align with the embedding model's optimal input length.", verbose_name='Child chunk size'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='embedding_service',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('ollama', 'Ollama'), ('xinference', 'Xinference'), ('custom', 'Custom API')], default='custom', help_text='Embedding provider used for new or reprocessed documents.', max_length=50, verbose_name='Embedding service'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='enable_hyde',
            field=models.BooleanField(default=False, help_text='Use LLM to generate a hypothetical answer, then search with its embedding instead of the original query.', verbose_name='Enable HyDE'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='enable_mmr',
            field=models.BooleanField(default=True, help_text='Apply Maximal Marginal Relevance diversification to reduce redundancy.', verbose_name='Enable MMR'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='enable_multi_query',
            field=models.BooleanField(default=False, help_text='Use LLM to generate multiple query variants for broader recall.', verbose_name='Enable multi-query'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='enable_query_rewrite',
            field=models.BooleanField(default=True, help_text='Use LLM to rewrite the query for better retrieval.', verbose_name='Enable query rewrite'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='mmr_lambda',
            field=models.FloatField(default=0.7, help_text='MMR diversity parameter: 0 = pure diversity, 1 = pure relevance.', verbose_name='MMR lambda'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='model_name',
            field=models.CharField(default='qwen3-vl-emb-2b', help_text='Model name used for embeddings.', max_length=100, verbose_name='Embedding model'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='multi_query_count',
            field=models.PositiveIntegerField(default=3, help_text='Number of query variants to generate (2-5).', verbose_name='Multi-query count'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='parent_child_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, documents are split into parent chunks (for context) and child chunks (for retrieval). Child chunks are indexed in the vector store; parent chunks are returned to the LLM.', verbose_name='Enable parent-child chunking'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='parent_chunk_overlap',
            field=models.PositiveIntegerField(default=200, help_text='Character overlap between parent chunks.', verbose_name='Parent chunk overlap'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='parent_chunk_size',
            field=models.PositiveIntegerField(default=2000, help_text='Character count for parent chunks.', verbose_name='Parent chunk size'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='reranker_api_key',
            field=models.CharField(blank=True, help_text='Authentication key for the reranker service.', max_length=500, null=True, verbose_name='Reranker API key'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='reranker_api_url',
            field=models.CharField(blank=True, help_text='Reranker endpoint. If empty, the embedding API base URL can be reused.', max_length=500, null=True, verbose_name='Reranker API URL'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='reranker_model_name',
            field=models.CharField(blank=True, default='Qwen3-VL-Reranker-2B', help_text='Model name used for reranking.', max_length=100, verbose_name='Reranker model'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='reranker_weight',
            field=models.FloatField(default=0.6, help_text='Weight of the reranker score in the composite scoring formula.', verbose_name='Reranker weight'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='rrf_weight',
            field=models.FloatField(default=0.3, help_text='Weight of the RRF fusion score in the composite scoring formula.', verbose_name='RRF weight'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='knowledgeglobalconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_knowledge_configs', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='generation_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Generation time'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to='knowledge.knowledgebase', verbose_name='Knowledge base'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='metadata_filter',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata filter'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='query',
            field=models.TextField(verbose_name='Query'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='retrieval_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Retrieval time'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='retrieved_chunks',
            field=models.JSONField(blank=True, default=list, verbose_name='Retrieved chunks'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='similarity_scores',
            field=models.JSONField(blank=True, default=list, verbose_name='Similarity scores'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='total_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Total time'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_queries', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
